# -----------------
# DCustomRPC Config
# -----------------
# Please read the README.md before asking for support.

client_id: 788567143558021162
# The client ID of the application you made on the Discord Developers page.

game_cycle:

  time_until_cycle: 10
  # The time until the game cycles.

  games:
    -
      large_image: enforcers21_thumbnail-04
      details: arro.digital
      
      
  # The list of games that it will cycle through.
